-- CSV 데이터 완전 업데이트 (difficulty, min/max_players 복구)
BEGIN;

UPDATE games SET difficulty = 1.6 WHERE id = 1;
UPDATE games SET difficulty = 1.62 WHERE id = 2;
UPDATE games SET difficulty = 2 WHERE id = 3;
UPDATE games SET difficulty = 1.33 WHERE id = 4;
UPDATE games SET difficulty = 1.16, min_players = 1, max_players = 4 WHERE id = 5;
UPDATE games SET difficulty = 1, min_players = 2, max_players = 12 WHERE id = 6;
UPDATE games SET difficulty = 2 WHERE id = 7;
UPDATE games SET difficulty = 1.7 WHERE id = 8;
UPDATE games SET difficulty = 1.7 WHERE id = 9;
UPDATE games SET difficulty = 2.5 WHERE id = 10;
UPDATE games SET difficulty = 3.92, min_players = 1, max_players = 4 WHERE id = 11;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 12;
UPDATE games SET difficulty = 1.7 WHERE id = 13;
UPDATE games SET min_players = 1, max_players = 4 WHERE id = 14;
UPDATE games SET difficulty = 1 WHERE id = 15;
UPDATE games SET difficulty = 1.13, min_players = 3, max_players = 7 WHERE id = 16;
UPDATE games SET difficulty = 1.66, min_players = 3, max_players = 5 WHERE id = 17;
UPDATE games SET difficulty = 2.5 WHERE id = 18;
UPDATE games SET difficulty = 1.12, min_players = 3, max_players = 6 WHERE id = 19;
UPDATE games SET difficulty = 1 WHERE id = 21;
UPDATE games SET difficulty = 1.28, min_players = 4, max_players = 8 WHERE id = 22;
UPDATE games SET difficulty = 1 WHERE id = 23;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 25;
UPDATE games SET difficulty = 2.5 WHERE id = 26;
UPDATE games SET difficulty = 1.71, min_players = 2, max_players = 6 WHERE id = 27;
UPDATE games SET difficulty = 1.82, min_players = 3, max_players = 8 WHERE id = 30;
UPDATE games SET difficulty = 2.34, min_players = 2, max_players = 2 WHERE id = 32;
UPDATE games SET difficulty = 1.19, min_players = 2, max_players = 4 WHERE id = 33;
UPDATE games SET difficulty = 3.38, min_players = 1, max_players = 4 WHERE id = 34;
UPDATE games SET difficulty = 1.74, min_players = 5, max_players = 10 WHERE id = 35;
UPDATE games SET min_players = 2, max_players = 11 WHERE id = 37;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 38;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 39;
UPDATE games SET difficulty = 1.47, min_players = 2, max_players = 2 WHERE id = 40;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 41;
UPDATE games SET min_players = 2, max_players = 8 WHERE id = 42;
UPDATE games SET difficulty = 1.71, min_players = 2, max_players = 4 WHERE id = 43;
UPDATE games SET difficulty = 3.84, min_players = 2, max_players = 4 WHERE id = 44;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 45;
UPDATE games SET difficulty = 2.5 WHERE id = 46;
UPDATE games SET difficulty = 2.5 WHERE id = 47;
UPDATE games SET difficulty = 2.5 WHERE id = 48;
UPDATE games SET difficulty = 1.82, min_players = 3, max_players = 6 WHERE id = 50;
UPDATE games SET difficulty = 2.5 WHERE id = 51;
UPDATE games SET difficulty = 2.5 WHERE id = 52;
UPDATE games SET difficulty = 2.5 WHERE id = 53;
UPDATE games SET difficulty = 1 WHERE id = 54;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 55;
UPDATE games SET difficulty = 1.33 WHERE id = 56;
UPDATE games SET difficulty = 1.13 WHERE id = 57;
UPDATE games SET difficulty = 3.74, min_players = 2, max_players = 5 WHERE id = 58;
UPDATE games SET difficulty = 1.63 WHERE id = 60;
UPDATE games SET difficulty = 1.65 WHERE id = 61;
UPDATE games SET difficulty = 2.48, min_players = 1, max_players = 5 WHERE id = 63;
UPDATE games SET difficulty = 1.67, min_players = 2, max_players = 7 WHERE id = 64;
UPDATE games SET difficulty = 2.5 WHERE id = 65;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 66;
UPDATE games SET difficulty = 1 WHERE id = 68;
UPDATE games SET difficulty = 1.26, min_players = 2, max_players = 99 WHERE id = 70;
UPDATE games SET difficulty = 2.14, min_players = 1, max_players = 2 WHERE id = 71;
UPDATE games SET min_players = 1 WHERE id = 72;
UPDATE games SET difficulty = 3, min_players = 2, max_players = 6 WHERE id = 73;
UPDATE games SET difficulty = 1.32, min_players = 3, max_players = 10 WHERE id = 74;
UPDATE games SET difficulty = 3.45, min_players = 1, max_players = 5 WHERE id = 75;
UPDATE games SET difficulty = 2.5 WHERE id = 77;
UPDATE games SET difficulty = 2.5 WHERE id = 78;
UPDATE games SET difficulty = 1, min_players = 1, max_players = 6 WHERE id = 79;
UPDATE games SET difficulty = 2.23, min_players = 2, max_players = 2 WHERE id = 80;
UPDATE games SET difficulty = 1.65, min_players = 1, max_players = 20 WHERE id = 81;
UPDATE games SET difficulty = 1.32, min_players = 2, max_players = 6 WHERE id = 82;
UPDATE games SET difficulty = 1 WHERE id = 83;
UPDATE games SET difficulty = 2.69, min_players = 2, max_players = 5 WHERE id = 84;
UPDATE games SET difficulty = 1 WHERE id = 85;
UPDATE games SET difficulty = 1.31, min_players = 2, max_players = 6 WHERE id = 86;
UPDATE games SET difficulty = 1.78, min_players = 2, max_players = 4 WHERE id = 87;
UPDATE games SET difficulty = 1.5 WHERE id = 88;
UPDATE games SET difficulty = 2.5 WHERE id = 89;
UPDATE games SET difficulty = 1.74, min_players = 5, max_players = 10 WHERE id = 90;
UPDATE games SET difficulty = 2.05, min_players = 2, max_players = 8 WHERE id = 91;
UPDATE games SET difficulty = 2 WHERE id = 92;
UPDATE games SET difficulty = 2.33, min_players = 1, max_players = 3 WHERE id = 94;
UPDATE games SET difficulty = 3.59, min_players = 1, max_players = 8 WHERE id = 95;
UPDATE games SET difficulty = 3.57, min_players = 1, max_players = 2 WHERE id = 96;
UPDATE games SET difficulty = 1.5 WHERE id = 97;
UPDATE games SET difficulty = 2.5 WHERE id = 98;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 100;
UPDATE games SET difficulty = 1.72, min_players = 2, max_players = 4 WHERE id = 101;
UPDATE games SET difficulty = 2.5 WHERE id = 102;
UPDATE games SET min_players = 2, max_players = 2 WHERE id = 103;
UPDATE games SET difficulty = 1.37, min_players = 2, max_players = 6 WHERE id = 104;
UPDATE games SET difficulty = 3.92, min_players = 1, max_players = 4 WHERE id = 105;
UPDATE games SET difficulty = 3.73, min_players = 3, max_players = 6 WHERE id = 106;
UPDATE games SET difficulty = 1.21, min_players = 2, max_players = 6 WHERE id = 107;
UPDATE games SET difficulty = 2.5 WHERE id = 108;
UPDATE games SET min_players = 2, max_players = 4 WHERE id = 109;
UPDATE games SET difficulty = 2.28, min_players = 1, max_players = 5 WHERE id = 110;
UPDATE games SET difficulty = 2.5 WHERE id = 112;
UPDATE games SET difficulty = 4.26, min_players = 2, max_players = 4 WHERE id = 113;
UPDATE games SET difficulty = 4, min_players = 3, max_players = 6 WHERE id = 114;
UPDATE games SET difficulty = 2.5 WHERE id = 115;
UPDATE games SET difficulty = 2.26, min_players = 3, max_players = 5 WHERE id = 116;
UPDATE games SET difficulty = 1.08, min_players = 2, max_players = 5 WHERE id = 117;
UPDATE games SET difficulty = 1 WHERE id = 118;
UPDATE games SET difficulty = 2 WHERE id = 120;
UPDATE games SET difficulty = 2 WHERE id = 121;
UPDATE games SET difficulty = 2.79, min_players = 2, max_players = 4 WHERE id = 122;
UPDATE games SET difficulty = 1.01, min_players = 2, max_players = 6 WHERE id = 123;
UPDATE games SET difficulty = 4.07, min_players = 1, max_players = 4 WHERE id = 124;
UPDATE games SET difficulty = 1.65, min_players = 2, max_players = 6 WHERE id = 126;
UPDATE games SET difficulty = 1.89, min_players = 1, max_players = 100 WHERE id = 127;
UPDATE games SET difficulty = 1 WHERE id = 128;
UPDATE games SET difficulty = 2.5 WHERE id = 129;
UPDATE games SET difficulty = 3.65, min_players = 2, max_players = 2 WHERE id = 130;
UPDATE games SET difficulty = 1 WHERE id = 131;
UPDATE games SET difficulty = 1 WHERE id = 132;
UPDATE games SET difficulty = 2.5 WHERE id = 133;
UPDATE games SET difficulty = 2.5 WHERE id = 134;
UPDATE games SET difficulty = 1.89, min_players = 2, max_players = 5 WHERE id = 135;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 136;
UPDATE games SET min_players = 2, max_players = 99 WHERE id = 138;
UPDATE games SET difficulty = 1.5, min_players = 2, max_players = 8 WHERE id = 140;
UPDATE games SET difficulty = 2.28, min_players = 3, max_players = 4 WHERE id = 141;
UPDATE games SET difficulty = 3.21, min_players = 1, max_players = 7 WHERE id = 142;
UPDATE games SET difficulty = 1.84, min_players = 1, max_players = 4 WHERE id = 143;
UPDATE games SET difficulty = 1 WHERE id = 144;
UPDATE games SET difficulty = 1.26, min_players = 2, max_players = 8 WHERE id = 146;
UPDATE games SET difficulty = 2.5 WHERE id = 147;
UPDATE games SET difficulty = 1.42, min_players = 2, max_players = 6 WHERE id = 148;
UPDATE games SET difficulty = 1 WHERE id = 149;
UPDATE games SET difficulty = 1.94, min_players = 2, max_players = 4 WHERE id = 150;
UPDATE games SET difficulty = 2.5 WHERE id = 151;
UPDATE games SET difficulty = 1.64, min_players = 2, max_players = 6 WHERE id = 152;
UPDATE games SET difficulty = 2 WHERE id = 153;
UPDATE games SET difficulty = 1.48, min_players = 6, max_players = 30 WHERE id = 154;
UPDATE games SET difficulty = 2.59, min_players = 2, max_players = 4 WHERE id = 155;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 156;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 157;
UPDATE games SET difficulty = 2.5, min_players = 1, max_players = 5 WHERE id = 158;
UPDATE games SET min_players = 1, max_players = 6 WHERE id = 159;
UPDATE games SET difficulty = 2.5 WHERE id = 160;
UPDATE games SET difficulty = 3.27, min_players = 1, max_players = 5 WHERE id = 162;
UPDATE games SET difficulty = 3.55, min_players = 2, max_players = 4 WHERE id = 163;
UPDATE games SET difficulty = 2.55, min_players = 1, max_players = 4 WHERE id = 164;
UPDATE games SET difficulty = 2.34, min_players = 3, max_players = 10 WHERE id = 165;
UPDATE games SET difficulty = 1.92, min_players = 2, max_players = 5 WHERE id = 166;
UPDATE games SET difficulty = 2.5 WHERE id = 167;
UPDATE games SET difficulty = 2.59, min_players = 3, max_players = 6 WHERE id = 168;
UPDATE games SET difficulty = 1.6, min_players = 2, max_players = 2 WHERE id = 169;
UPDATE games SET difficulty = 2.39, min_players = 2, max_players = 4 WHERE id = 170;
UPDATE games SET min_players = 1, max_players = 1 WHERE id = 174;
UPDATE games SET difficulty = 3.27, min_players = 3, max_players = 5 WHERE id = 175;
UPDATE games SET difficulty = 1.5 WHERE id = 176;
UPDATE games SET difficulty = 2 WHERE id = 177;
UPDATE games SET difficulty = 1.02 WHERE id = 178;
UPDATE games SET difficulty = 1.19, min_players = 2, max_players = 6 WHERE id = 179;
UPDATE games SET difficulty = 1.2 WHERE id = 180;
UPDATE games SET difficulty = 1 WHERE id = 181;
UPDATE games SET difficulty = 1.5 WHERE id = 182;
UPDATE games SET difficulty = 2.5, min_players = 1, max_players = 4 WHERE id = 183;
UPDATE games SET difficulty = 1 WHERE id = 184;
UPDATE games SET difficulty = 1 WHERE id = 185;
UPDATE games SET difficulty = 1.75, min_players = 1, max_players = 8 WHERE id = 186;
UPDATE games SET difficulty = 1, min_players = 1, max_players = 4 WHERE id = 187;
UPDATE games SET difficulty = 1 WHERE id = 188;
UPDATE games SET difficulty = 1.56, min_players = 3, max_players = 5 WHERE id = 189;
UPDATE games SET min_players = 2, max_players = 6 WHERE id = 190;
UPDATE games SET difficulty = 1.04, min_players = 2, max_players = 8 WHERE id = 191;
UPDATE games SET difficulty = 1.69, min_players = 2, max_players = 4 WHERE id = 192;
UPDATE games SET difficulty = 1 WHERE id = 193;
UPDATE games SET difficulty = 2.5 WHERE id = 197;
UPDATE games SET difficulty = 2.6 WHERE id = 198;
UPDATE games SET difficulty = 2.5 WHERE id = 200;
UPDATE games SET difficulty = 2.5 WHERE id = 201;
UPDATE games SET difficulty = 2.5 WHERE id = 203;
UPDATE games SET difficulty = 2.48 WHERE id = 204;
UPDATE games SET difficulty = 1.19 WHERE id = 205;
UPDATE games SET difficulty = 1.07 WHERE id = 207;
UPDATE games SET difficulty = 2.6 WHERE id = 208;
UPDATE games SET difficulty = 2.23 WHERE id = 209;
UPDATE games SET difficulty = 2.23 WHERE id = 210;
UPDATE games SET difficulty = 1.81 WHERE id = 211;
UPDATE games SET difficulty = 1.91 WHERE id = 212;
UPDATE games SET difficulty = 3 WHERE id = 213;
UPDATE games SET difficulty = 3 WHERE id = 214;
UPDATE games SET difficulty = 3 WHERE id = 215;

COMMIT;